### ISSUE TITLE
Applicazione delle policy per CNS

### ISSUE THREAD

**Issue by lucabonuccelli** [italia/cie-cns-apache-docker#1]
Non pare che si tenga conto delle policy che permettono di distinguire una certificato generico  emesso da una CA che emette ANCHE cns da una CNS.

In particolare:

L’estensione Certificate Policies (Object ID: 2.5.29.32)  DEVE  contenere l’object id della Certificate  Policy  (CP)  e  l’URI  (Uniform  Resource   Identifier)  che  punta  al  Certificate  Practice  Statement (CPS) nel rispetto del quale il certificatore ha emesso il certificato. Detto object id è definito e pubblicizzato dal certificatore.  A far data dal mese di maggio 2005 l’estensione DEVE inoltre contenere l’object id “1.3.76.16.2.1”  e il qualifier “userNotice” di tipo “explicitText” con il seguente contenuto: ”Identifies X.509 authentication certificates issued for the italian National Service Card (CNS) project in according to the italian regulation"

**Comment by lucabonuccelli** [comment]
Dato che ho posto la issue propongo una strategia di soluzione:

inserire nelle direttive una rewrite url condizionata alla presenza di un certificato client che  abbia la policy sopra indicata correttamente valorizzata.

qualcosa di simile a 
`RewriteCond test
RewriteRule  errorpage.php`
Dove test ha il significato: NOT ( il qualifier “userNotice” di tipo “explicitText” con il seguente contenuto: ”Identifies X.509 authentication certificates issued for the italian National Service Card (CNS) project in according to the italian regulation")

**Comment by amusarra** [comment]
@lucabonuccelli ho provato a utilizzare la funzione PeerExtList specificando l'OID interessato ma sembra non funzionare. 
Ho utilizzato la funzione insieme SSLRequire così come indicato sulla documentazione di Apache https://httpd.apache.org/docs/2.4/mod/mod_ssl.html ma sembra non funzionare. 

Tu hai già avuto esperienza a fare il check direttamente su Apache? Sembra complicato fare check sulle Certificate Extensions da Apache. In altri progetti, ho solitamente demandato ad altri componenti della catena, come per esempio Oracle OAM o altri simili.

**Comment by lucabonuccelli** [comment]
si, ho esperienza purtroppo però su versioni più datate.
Appena ho un poco di tempo replico il caso su questa versione e cerco di farti il mio contributo.

**Comment by amusarra** [comment]
Se riesci a trovare posta pure le configurazioni anche se su versioni di Apache più datate, a meno che non sia una versione 1.x. Grazie.

**Comment by amusarra** [comment]
Ciao @lucabonuccelli ho scritto a Joe Orton (di RedHat) che segue il progetto HTTPD e ha risposto che con la funzione **PeerExtList** non è possibile verificare valori per **estensioni che sono strutturate** (caso della Certificate Policies).

> This isn't going to be possible for structured extension values, you'll 
> need custom code to check the policy value.
> 
> Regards, Joe

**Comment by lucabonuccelli** [comment]
eccomi.
l'unica soluzione percorribile pare essere l'uso di 
https://httpd.apache.org/docs/2.4/mod/mod_ext_filter.html
Che però è da evitare  in ambienete di esercizio.

quello che possiamo fare è documentare e  predisporre una test page c he illustri cosa deve essere aggiunto al livello applicativo.

**Comment by amusarra** [comment]
Eviterei l'uso dei filter di Apache. A scopo esemplificativo direi di fare un controllo lato applicativo (sulla Welcome Page), in questo caso PHP.

In genere su altri progetti Apache HTTPD assume il ruolo di Reverse Proxy verso application server che potrebbero essere Java, PHP, Ruby, etc. Per esempio, se l'applicazione fosse Java, basterebbe un Servlet Filter.

In architetture più complesse, sono i sistemi di IDM (come Oracle OID/IAM, SiteMinder, OpenAM, etc.) che generalmente eseguono questo compito di check.  

Questa sera a casa predispongo un check lato applicativo.

**Comment by amusarra** [comment]
Ciao @lucabonuccelli Ho appena rilasciato la versione 1.2.0 che implementa il check della Policy. Fammi sapere in caso chiudo la poi la issue.

**Comment by lucabonuccelli** [comment]
scusa il ritardo, sono giorni terribili...
ottimo, hai fatto bene a chiudere ;)

**Comment by amusarra** [comment]
Tranquillo. Ho anche aggiunto l’aggiornamento una volta al giorno dei certificati.
