### ISSUE TITLE
Secure JSON API

### ISSUE THREAD

**Issue by salvorapi** [italia/cie-cns-apache-docker#10]
Salve,

posso proporre la possibilità di aggiungere oltre alla pagina secure  una forma di API che ritorna le informazioni della pagina in formato JSON ?

Grazie.

**Comment by amusarra** [comment]
Ciao @salvorapi 
Esiste il figlio “maggiorato” di questo progetto che trovi https://github.com/amusarra/docker-apache-ssl-tls-mutual-authentication che ha questa funzione e include il progetto httpbin. Prova a dare uno sguardo. Vorresti una cosa del genere anche qui?

**Comment by amusarra** [comment]
Ciao @salvorapi mi fai sapere se poi il figlio "maggiorato" di questo progetto rispondeva alla tua richiesta? Eventualmente vedrò d'integrare httpbin anche su questo progetto. Fammi sapere. Grazie.

**Comment by salvorapi** [comment]
Ciao @amusarra,

ho perso il thread e non ho avuto modo di risponderti.
Sì, sicuramente la versione estesa è proprio quello che serviva a me 👍 

Grazie!

Salvo.
