### ISSUE TITLE
Certificati SSL cns.dontesta.it Scaduti + Errore python\r parse-gov-certs.py 

### ISSUE THREAD

**Issue by alessioacella** [italia/cie-cns-apache-docker#11]
Buongiorno, 

Segnalo che i certificati SSL cns.dontesta.it sono scaduti ad Aprile 2020.
E' possibile rilasciare direttamente un aggiornamento con i certificati aggiornati?

Segnalo inoltre la presenza di un errore di codifica del file parse-gov-certs.py dove i line breaks sono stati segnalati con \r (codifica ambiente windows) -> codifica incompatibile per ambienti unix (risolto in locale con l'utilizzo di VIM e della codifica opportuna :set ff=unix).

Grazie,
Alessio

**Comment by amusarra** [comment]
Ciao @alessioacella ti ringrazio molto della segnalazione. Appena possibile provvederò ad aggiornare i certificati di esempio.
Per il file `parse-gov-certs.py` è davvero strano, io eseguo sempre su ambiente unix/linux e non ho riscontrato il problema, verificherò.

Grazie.

**Comment by amusarra** [comment]
Ciao @alessioacella riguardo lo script mi risulta in LF (Line Feed, formato unix). Forse quello che indenti tu è la mancanza dell'LF sull'ultima riga, ma quello non è un problema.

<img width="1031" alt="Schermata 2020-09-15 alle 10 48 22" src="https://user-images.githubusercontent.com/708110/93188217-02cac700-f741-11ea-9083-2c80ff6e1759.png">

**Comment by amusarra** [comment]
Ciao @alessioacella per informarti che ho appena eseguito il rilascio della versione 1.3.9 che risolve le due issue da te segnalate. Chiudo questa issue.

**Comment by alessioacella** [comment]
Ti ringrazio @amusarra per il supporto.

Alessio
