### ISSUE TITLE
Errore di avvio del container ed altro

### ISSUE THREAD

**Issue by cl4r0s** [italia/cie-cns-apache-docker#12]
Salve
Vorrei segnalare che il comando di avvio corretto dell'immagine docker è il seguente:

docker run --hostname cns.dontesta.it -i -t -d -p 10443:10443 --name=cie-cns italia/cie-cns-apache-docker:latest

Senza il parametro hostname, apache non può partire poichè la variabile Servername non trova riscontro nel file host.

Inoltre il 14 dicembre il certificato andrà in scadenza e sarebbe bene rinnovarlo.

Saluti e grazie per il vostro lavoro

**Comment by amusarra** [comment]
Grazie per la segnalazione. Riguardo il README che pensavo di aver aggiornato.

Sul certificato so che è in scadenza, appena possibile sarà rinnovato.

Grazie ancora.

**Comment by amusarra** [comment]
Con la nuova versione ho aggiornato il certificato SSL. Il comando Docker indicato sulla documentazione è corretto, non è necessario specificare hostname. Puoi vedere il comando eseguito dal vivo in questo tutorial https://youtube.com/watch?v=TcAzn1POhsM&feature=share dal minuto 24.

Grazie ancora per la segnalazione.
