### ISSUE TITLE
CURL su /secure

### ISSUE THREAD

**Issue by AlexVexa** [italia/cie-cns-apache-docker#13]
Ciao, è possibile effettuare lo scraping sulla pagina secure? Vorrei acquisire determinati dati tramite CURL ma non capisco come gestire le chiavi della carta, è possibile eventualmente acquisire la chiave privata, o questo genere di operazioni non è disponibile con questo genere di token?

**Comment by amusarra** [comment]
Ciao Alessandro. Non è possibile farlo. La sicurezza nell'uso della carta consiste proprio in questo, tutte le operazioni crittografiche avvengono al suo interno e la chiave privata non può essere esportata. Chiudo la issue perchè non è una issue. Grazie.

**Comment by AlexVexa** [comment]
Quindi mi confermi che, nonostante io sia in possesso di carta CNS e dei dati, e nonostante la carta rimanga SEMPRE collegata al PC, non c'è modo per farla comunicare con un sistema come il CURL in php o altro? Non ci sono "dati" utilizzabili per arrivarealla pagina /secure tramite cURL e non tramite, per esempio, barra degli indirizzi di un browser?

**Comment by amusarra** [comment]
> Quindi mi confermi che, nonostante io sia in possesso di carta CNS e dei dati, e nonostante la carta rimanga SEMPRE collegata al PC, non c'è modo per farla comunicare con un sistema come il CURL in php o altro? Non ci sono "dati" utilizzabili per arrivarealla pagina /secure tramite cURL e non tramite, per esempio, barra degli indirizzi di un browser?

Non so il tuo livello di conoscenza in materia. In teoria sarebbe possibile farlo se la tua versione di cURL supportasse l'integrazione con lo standard PKCS#11. Ti ricordo che la CIE ha un modulo custom PKCS#11, che poi è quello distribuito con il Middleware CIE. Appena avrò del tempo questo potrebbe essere un tema per il mio prossimo articolo per il mio blog. Grazie

**Comment by AlexVexa** [comment]
Ciao, grazie mille per la risposta, onestamente pensavo che la CNS avesse standard PKCS#7.
Considerando che in questo momento la chiamata cURL avviene in locale, non dovrebbe essere un problema aggiornare l'integrazione al PKCS#11. Avresti qualche consiglio su qualche guida per capirne di più?

**Comment by amusarra** [comment]
> Ciao, grazie mille per la risposta, onestamente pensavo che la CNS avesse standard PKCS#7.
> 
> Considerando che in questo momento la chiamata cURL avviene in locale, non dovrebbe essere un problema aggiornare l'integrazione al PKCS#11. Avresti qualche consiglio su qualche guida per capirne di più? 

Allora, gli standard dello stack PKI sono parecchi. Lo standard PKCS#7 definisce lo standard per il formato "contenitore" per certificati x509. Lo standard PKCS#11 definisce invece un set di API indipendenti dalla piattaforma per i token crittografici, come per esempio HSM e Smart Card. 

Venendo adesso al cURL, da quello che ricordo, attraverso il parametro engine puoi specificare lo standard e in questo caso pkcs11, in questo modo il cURL dovrebbe essere nelle condizioni di accedere alla CIE o CNS, richiedendo il PIN ed eseguendo il processo di mutua autenticazione. Dovrei averti dato un'altra buona dritta.

**Comment by AlexVexa** [comment]
Nei convertitori da cUrl a PHP il campo --engine pkcs11 viene ignorato e quindi il lettore non viene di conseguenza letto (se passato il codice in un file php)...
Il mio obiettivo era acquisire tramite cUrl i dati della chiave della pagina secure... quindi facendo un "curl --engine pkcs11 https://entra-cns-cie.dontesta.it/" in console con il pkcs11 installato nell'openSSL ottengo l'html della pagina però senza i dati della CNS (cioè il classico errore di quando risulta scollegato), idee sul perchè?

**Comment by amusarra** [comment]
Perchè non basta utilizzare il comando in quel modo. Ci sono di mezzo anche le URI PKCS#11 e quindi l'RFC7512. In breve, tramite le URI che devi passare a cURL gli dici dove anche a prendere i certificati. Come ti avevo già scritto al momento non ho il tempo di metterci su, ti coniglio per questo motivo di scrivere direttamente sul canale CIE su Slack https://developersitalia.slack.com/archives/C75U26411 Ciao.

**Comment by AlexVexa** [comment]
Ciao, grazie mille per le risposte, mi puoi far aggiungere al gruppo di slack? Con il semplice accesso del mio account non mi è possibile

**Comment by amusarra** [comment]
L'accesso è gratuito basta andare su https://developersitalia.slack.com/ e accedere o registrarti.

**Comment by AlexVexa** [comment]
> L'accesso è gratuito basta andare su https://developersitalia.slack.com/ e accedere o registrarti.

Forse hanno cambiato l'accesso allo slack. Mi dice che posso accedere/registrarmi solo ed esclusivamente con account di domini di questo tipo: @teamdigitale.governo.it o @agid.gov.it

**Comment by amusarra** [comment]
Inviami la tua email che provo ad inviarti l'invito.

**Comment by AlexVexa** [comment]
> Inviami la tua email che provo ad inviarti l'invito.

aldeca96@gmail.com
