### ISSUE TITLE
cna authenticator

### ISSUE THREAD

**Issue by nicolardi** [italia/cie-cns-apache-docker#15]

**Comment by amusarra** [comment]
Ciao @nicolardi potresti descrivere il problema che vorresti segnalare?

Grazie.

**Comment by nicolardi** [comment]
Ciao,

Assolutamente nessuno.
Probabilmente ho sbagliato a cliccare su qualche pulsante scusa

Massimo

**Comment by amusarra** [comment]
Nessun problema. Allora chiudo la issue. Per ogni dubbio e/o chiarimento fammi sapere.
