### ISSUE TITLE
Several vulnerabilities in old version of Apache HTTP

### ISSUE THREAD

**Issue by Valeri0p** [italia/cie-cns-apache-docker#16]
As the title says, this project should probably get updated. Official list of vulns, some are marked as "critical":
https://httpd.apache.org/security/vulnerabilities_24.html

**Comment by amusarra** [comment]
Hi @Valeri0p 
I had planned an update of the Apache HTTP server. I will do it as soon as possible.

Thank you.

**Comment by amusarra** [comment]
Hi @Valeri0p 
I had released the new version 2.2.0.
