### ISSUE TITLE
Autenticazione modalità desktop con mobile e Autenticazione modalità mobile 

### ISSUE THREAD

**Issue by FrancescoPenasa** [italia/cie-cns-apache-docker#19]
Salve, 
inanzitutto complimenti per il container docker che funziona perfettamente in caso di autenticazione modalità desktop,
volevo chiedere se ha previsto dei nuovi rilasci per supportare anche le autenticazioni modalità desktop con mobile e modalità mobile 
`https://www.cartaidentita.interno.gov.it/cittadini/entra-con-cie/` 
`https://www.cartaidentita.interno.gov.it/downloads/2021/02/ibrido.pdf`

**Comment by amusarra** [comment]
Ciao @FrancescoPenasa ti ringrazio per l'apprezzamento. Al momento non sono a piano rilasci per aggiungere il supporto per le altre modalità di autenticazione previste.
