### ISSUE TITLE
Build fallita su Windows

### ISSUE THREAD

**Issue by cirolaferrara** [italia/cie-cns-apache-docker#20]
Il comando docker di build fallisce

`docker build -t cie-cns-apache-docker .`

Restituisce l'errore 

```
/usr/bin/env: 'python2\r': No such file or directory
```

Questo è dovuto ad un errato carattere di fine riga.

**Comment by amusarra** [comment]
Ciao @cirolaferrara 
Ti ringrazio per la tua segnalazione. Purtroppo Windows non è una delle piattaforme di build su cui ho eseguito i test, e che ho escluso a priori; la build dell'immagine Docker finale fa infatti uso del tool make, tipico dei sistemi Unix/Linux.

Non ho neanche modo di eseguire un test per il fatto che non dispongo di una macchina Windows, solitamente lavoro su Linux e macOS.

Se usi un sistema Windows è molto probabile che l'azione di clone abbia aggiunto su file di testo il carattere di CR (\r o Carriage Return). Per evitare questa **odiosa manipolazione**, dovresti eseguire il clone del repository specificando di lasciare inalterato il line endings dei file in questo modo  `--config core.autocrlf=input` (dirattamente sul comando clone).

Ti chiedo quindi di fare nuovamente una prova di clone con l'opzione indicata.

Fammi sapere.

Grazie.

**Comment by cirolaferrara** [comment]
Nel mio caso `git config --global core.autocrlf input` ha funzionato perfettamente. Grazie
