### ISSUE TITLE
 AH00558: apache2: Could not reliably determine the server's fully qualified domain name....

### ISSUE THREAD

**Issue by rdipalmadac** [italia/cie-cns-apache-docker#21]
Buongiorno.
Innanzitutto grazie per la condivisione del vs lavoro,
Vorrei segnalare che utilizzando docker-compose ottengo questo messaggio:
` AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.2. Set the 'ServerName' directive globally to suppress this message`.
Posso risolvere in quale maniera?
Grazie

**Comment by amusarra** [comment]
Ciao @rdipalmadac mi fa piacere che questo progetto sia utile per i tuoi scopi.

Il messaggio che vedi sui log è a scopo informativo e un errore AH00558 non impedirà il corretto funzionamento di Apache.

Per maggiori informazioni ti consiglio di fare riferimento alla documentazione di Apache o leggere questo articolo molto esaustivo https://www.digitalocean.com/community/tutorials/apache-configuration-error-ah00558-could-not-reliably-determine-the-server-s-fully-qualified-domain-name

Se non ci sono ulteriori dubbi e/o chiarimenti, ti chiederei la chiusura della issue.

Grazie.

**Comment by rdipalmadac** [comment]
Salve. In effetti ho segnalato il problema perchè sulla mia vm di test, il docker-compose si evolve fino a quel punto. Dopo non prosegue più rimanendo sospeso. Giusto per la pecisione il SO è ubuntu 22.04 aggiornato a ieri. Magari a qualcun altro non succede.
Grazie e buon lavoro

**Comment by amusarra** [comment]
> Salve. In effetti ho segnalato il problema perchè sulla mia vm di test, il docker-compose si evolve fino a quel punto. Dopo non prosegue più rimanendo sospeso. Giusto per la pecisione il SO è ubuntu 22.04 aggiornato a ieri. Magari a qualcun altro non succede.
> Grazie e buon lavoro

È corretto il comportamento del Docker Compose quando non avviato in modalità detached; e mostra sullo standard output (quindi in console) i log dell’applicazione e in questo caso anche quelli di Apache.

**Comment by rdipalmadac** [comment]
Grazie del supporto.
