### ISSUE TITLE
File 000-default.conf

### ISSUE THREAD

**Issue by rdipalmadac** [italia/cie-cns-apache-docker#22]
Rieccomi.
Ho notato che nell'illustrazione del file Docker si fa riferimento a:
`COPY configs/httpd/000-default.conf /etc/apache2/sites-available/'
che però non esiste nella cartella 'configs'
Magari è superato magari no.
Puoi delucidarmi?
Grazie

**Comment by amusarra** [comment]
Ciao @rdipalmadac forse si tratta di un refuso. Vedrò di controllare nei prossimi giorni.

Grazie.

**Comment by amusarra** [comment]
Ciao @rdipalmadac 
L'errore è stato corretto sul file README. Chiudo la issue.

Grazie.
