### ISSUE TITLE
Documentare come usare OCSP e/o CRL

### ISSUE THREAD

**Issue by alranel** [italia/cie-cns-apache-docker#3]
Al momento il web server predisposto da questa immagine Docker non verifica se il certificato sia stato revocato.
Sarebbe utile configurarlo in modo che esegua questa verifica via OCSP, gestendo anche il caso dell'interrogazione fallita (mediante visualizzazione di una pagina di errore oppure interrogazione di una CRL locale scaricata periodicamente dall'URL ufficiale).

La configurazione potrebbe anche essere lasciata commentata, ma in tal caso dovrebbe essere documentata nel README.
Questa cosa andrebbe fatta sia per CIE sia per CNS.

Concordi @lucabonuccelli?

**Comment by lucabonuccelli** [comment]
Salve, 
(IMHO) entrambe le strade sono valide.
C'è da tenere di conto 3 aspetti:
Affidabilità del controllo
- con ocsp nessuno 
- con CRL in funzione del ritardo nell'aggiornamento della CRL locale
semplicità di gestione 
- ocsp molto semplice, basta avere connettività
- CRL occorre scaricare le CRL
robustezza ad un disservizio nel raggiungere la CA
- con oscp il disservizio si propaga
- con CRL il disservizio non si propaga fino alla scadenza della copia locale

Nella mia esperienza oggi si utilizza ocsp e in caso di disservizio della CA (molto raro ma possibile) viene attivato l'uso della crl copiata in locale precedentemente .

E' da tenere di conto che l'indisponibilità di un servizio ocsp di una CA accreditata come servizio fiduciario, pur possibile, è  da considerarsi molto raro.

Tutto questo detto, per attivare ocsp sulla configurazione attuale dovrebbe bastare inserire queste righe:

`SSLUseStapling On`
`SSLStaplingCache shmcb:${APACHE_RUN_DIR}/ssl_stapling(32768)`

in ssl.conf come ultima direttiva prima dei blocchi di virtualhosts

**Comment by amusarra** [comment]
Buongiorno.
Fin dalla prima versione del progetto, l'**OCSP Stapling** è attivo e la configurazione è presente all'interno del file di configurazione [configs/httpd/ssl-params.conf](https://github.com/italia/cie-cns-apache-docker/blob/1d37e92a30bcbd5077a506caa50dca2f1b8b6625/configs/httpd/ssl-params.conf#L11)

L'evidenza dell'attivazione è visibile anche dal test eseguito via ssllabs.
<img width="597" alt="ssllabs_cns_dontesta_it" src="https://user-images.githubusercontent.com/708110/50890344-4d3b6280-13fa-11e9-8f6f-b2c50cf737f4.png">

L'output di questo comando mostra una sezione che dice se il server web ha risposto con i dati OCSP. 

`echo QUIT | openssl s_client -connect cns.dontesta.it:443 -status 2> /dev/null | grep -A 17 'OCSP response:' | grep -B 17 'Next Update'`

<img width="1351" alt="ocsp_test" src="https://user-images.githubusercontent.com/708110/50890637-d9e62080-13fa-11e9-90b0-c8014c7adb52.png">

Per completezza allegato l'esito completo 
[SSL Server Test_ cns.dontesta.it (Powered by Qualys SSL Labs).pdf](https://github.com/italia/cie-cns-apache-docker/files/2740206/SSL.Server.Test_.cns.dontesta.it.Powered.by.Qualys.SSL.Labs.pdf)

Quello che non ho preferito attivare di default è l'OCSP per la validazione della chain dei certificati lato client.

Aggiornerò il README con qualche nota sull'OCSP.

Grazie.

**Comment by amusarra** [comment]
Ciao @alranel e @lucabonuccelli 
Ho aggiornato la documentazione circa le note su OCSP e CRL.

Fatemi sapere se posso chiudere la issue.

Grazie e buon weekend

**Comment by amusarra** [comment]
Credo che la issue possa essere chiusa.
