### ISSUE TITLE
Gestire certificato mancante?

### ISSUE THREAD

**Issue by alranel** [italia/cie-cns-apache-docker#4]
Al momento, se non erro, questa immagine Docker avvia un webserver che richiede CIE o CNS per qualsiasi richiesta; in mancanza, l'utente otterrà un errore generico del suo browser.

Non sono sicuro che sia fattibile, ma sarebbe utile mostrare come restituire una pagina HTML custom in mancanza di certificato client: tale pagina spiegherebbe all'utente che deve posizionare la CIE o la CNS sul lettore, magari a sua volta rimandando a pagine di help, e includerebbe un tasto per riprovare l'accesso.

**Comment by amusarra** [comment]
Si, è una configurazione base.
In ogni caso sarebbe possibile utilizzare un [Custom Errors Responses](https://httpd.apache.org/docs/2.4/custom-error.html) sfruttando la direttiva di Apache 2.4

**Comment by lucabonuccelli** [comment]
se può essere utile questa strategia diversa:

```
RewriteCond %{SSL:SSL_CLIENT_VERIFY} !^SUCCESS$
RewriteRule .* http://landing.page.di.cortesia [L,R,QSA]
```

**Comment by amusarra** [comment]
Ciao @alranel e @lucabonuccelli 

La configurazione attuale, prevede un'autenticazione molto forte, `SSLVerifyClient` impostato al valore `require`.

**Gli errori SSL/TLS si verificano a livello TCP**, _il che significa che la connessione non arriva al punto in cui può essere gestita dalla gestione degli errori standard di Apache_ e reindirizzata a una pagina di errore personalizzata.

C'è un vecchio modulo Apache chiamato **mod_ssl_error** (https://bitbucket.org/wagnersolutions/mod-ssl-error) che fa esattamente quello che vorresti, ma richiede una compilazione e installazione manuale. F. Wagner ha reso compatibile questo modulo per la versione 2.4 di Apache.

La soluzione eventualmente da adottare, è quella d'impostare `SSLVerifyClient` con il valore `optional`  
e aggiungere la configurazione suggerita da @lucabonuccelli che in caso di verifica fallita del certificato client (check sulla variabile `SSL_CLIENT_VERIFY`) esegua poi il redirect verso una risorsa (da configurare).

Vi aggiorno.

**Comment by amusarra** [comment]
Ciao @alranel e @lucabonuccelli 
Ho appena rilascio la versione 1.3.2 che in breve:

- Aggiunta interfaccia utente meno "spartana"
- Aggiunta possibilità per configurare il parametro SSLVerifyClient
- Aggiunta la configurazione Apache per la separazione di una zona pubblica e una zona sicura

La nuova release è già disponibile all'indirizzo https://cns.dontesta.it

Fatemi sapere che in caso chiudo la issue.

Grazie.
Antonio.

**Comment by amusarra** [comment]
Credo che la issue possa essere chiusa.
