### ISSUE TITLE
Certificati Let's Encrypt revocati

### ISSUE THREAD

**Issue by salvorapi** [italia/cie-cns-apache-docker#9]
Buonasera,

ci sono i certificati di Let's Encrypt che sono stati revocati e non è possibile accedere all'interfaccia web.

**Comment by amusarra** [comment]
Ciao @salvorapi 
Ti ringrazio della segnalazione a breve provvederò all’aggiornamento.

**Comment by amusarra** [comment]
Ciao @salvorapi con la nuova release 1.3.9 ho aggiornato i certificati. Chiudo la issue. Grazie.
